dist: bionic
sudo: true
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb
  - sudo dpkg -i hugo_0.58.3_Linux-64bit.deb
script:
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name $GITHUB_USERNAME
  - git remote rm origin
  - git remote add origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
  - git symbolic-ref HEAD refs/heads/master
  - chmod +x setup.sh
  - ./setup.sh
  - hugo -d ../generated
  - git checkout origin/gh-pages
  - git pull
  - cp -r ../generated/* .
  - git add .
  - git commit -m "Add new content $(date '+%Y-%m-%d %H:%M:%S')"
  - git push
