dist: bionic
sudo: true
addons:
  apt:
    update: true
    packages:
    - hugo

script:
  - git config --global user.email $GITHUB_EMAIL
  - git config --global user.name $GITHUB_USERNAME
  - git remote rm origin
  - git remove add origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
  - git symbolic-ref HEAD ref/heads/master
  - chmod +x setup.sh
  - ./setup.sh
  - hugo -d ../generated 
  - git checkout gh-pages
  - git pull
  - cp ../generated/* .
  - git add .
  - git commit -m "Add new content `date '+%Y-%m-%d %H:%M:%S'`"
  - git push
